EMAIL_DOMAINS = [
    "@mailworld.com", "@globalmail.com", "@universenet.org", "@planetmail.net",
    "@mailgalaxy.biz", "@cometmail.co", "@starbox.io", "@nebulae.email",
    "@skyvaults.org", "@orbitmail.com", "@cosmicpost.net", "@lunarletters.com",
    "@solarmails.com", "@interstellars.com", "@galacticinbox.org", "@spacemail.net",
    "@quantummails.com", "@echoverse.com", "@tidalmail.com", "@aethermail.net",
    "@voidbox.co", "@stellarflares.com", "@dawnmail.org", "@twilightpost.com",
    "@eventideemails.net", "@midnightmail.co", "@daybreakmail.com", "@auroramail.io",
    "@dusktodawn.org", "@sunrisepost.net", "@sunsetmails.com", "@highnoonmail.com",
    "@cloudcomet.com", "@skyhigh.net", "@stratocumulus.org", "@cirrusclouds.co",
    "@nimbostratus.net", "@cumulonimbus.com", "@mystmail.org", "@etherbox.net",
    "@arcadianmail.com", "@utopianpost.co", "@edenmail.io", "@elysiumletters.org",
    "@nirvanamails.net", "@shangrilaemail.com", "@avaloninbox.com", "@atlantispost.net",
    "@olympusmails.org", "@valhallamail.com", "@asgardemails.co", "@midgardmessages.net",
    "@vistamail.com", "@horizonpost.org", "@peakmails.net", "@summitbox.com",
    "@crestmail.co", "@pinnaclepost.io", "@zenithemails.org", "@apexmail.net",
    "@acmemails.com", "@polarispost.co", "@northstarinbox.net", "@stellarpath.org",
    "@galaxygate.com", "@cosmosconnect.net", "@universeinbox.co", "@astralmails.io",
    "@astromails.org", "@spacestation.net", "@intergalacticmail.com", "@extraterrestrialpost.co",
    "@alieninbox.io", "@starfleetmails.org", "@federationpost.net", "@planetarymail.com",
    "@moonbaseemail.co", "@saturnrings.io", "@jupiterpost.org", "@marsmails.net",
    "@venusinbox.com", "@mercurymails.co", "@neptunepost.net", "@plutonmail.org",
    "@andromedamail.com", "@milkywaypost.net", "@cosmiccluster.co", "@blackholeinbox.io",
    "@supernovamails.org", "@nebulapost.net", "@quasarmail.com", "@pulsaremail.co"
]

TOP_EMAIL_DOMAINS = [
    '@gmail.com',
    '@yahoo.com',
    '@outlook.com',
    '@hotmail.com',
    '@icloud.com',
    '@aol.com',
    '@mail.com',
    '@gmx.com',
    '@live.com',
    '@yandex.com',
    '@qq.com',
    '@163.com',
    '@126.com',
    '@protonmail.com',
    '@zoho.com',
    '@rediffmail.com',
]

URL_PERSONAL_LIST = [
    "https://johnsmith.dev",
    "https://janesmithportfolio.com",
    "https://mikeross.tech/blog",
    "https://sarahconnor.media",
    "https://alexjohnson.info",
    "https://emilyclark.art",
    "https://davidmiller.photography",
    "https://lisawong.design",
    "https://tomwilson.engineer",
    "https://racheladams.writer",
    "https://stevenwright.architect",
    "https://juliechen.blogger",
    "https://kevinbrown.music",
    "https://monicagarcia.lawyer",
    "https://chriswhite.health",
    "https://samuelroberts.finance",
    "https://nataliecook.education",
    "https://ethanward.science",
    "https://dianamorris.coach",
    "https://garyjames.consulting",
    "https://hannahmartin.events",
    "https://laurajackson.fashion",
    "https://brandonlee.realestate",
    "https://jessicathompson.travel",
    "https://aaronhall.game",
    "https://karenlopez.fit",
    "https://andrewhill.photo",
    "https://melissaroberts.cafe",
    "https://joshuakim.shop",
    "https://vanessalee.news",
    "https://briancox.space",
    "https://amandawilson.tech",
    "https://gregorydavis.solutions",
    "https://sophiamartinez.studio",
    "https://derekjohnson.vet",
    "https://nicolebrown.charity",
    "https://michaelscott.farm",
    "https://lindajones.wine",
    "https://jasonwalker.toys",
    "https://oliviamartin.pets",
    "https://matthewrobinson.tools",
    "https://laurasmith.flowers",
    "https://peterjohnson.coffee",
    "https://emmaroberts.market",
    "https://jacobwilson.trade",
    "https://danielgarcia.camp",
    "https://rachelgreen.eco",
    "https://chrisevans.bike",
    "https://kellyclarkson.book",
    "https://tonystark.invest",
    "https://angelawhite.store",
    "https://brucewayne.club",
    "https://clarkkent.news",
    "https://dianaprince.org",
    "https://peterparker.chat",
    "https://stevejobs.bio",
    "https://elonmusk.life",
    "https://jeffbezos.money",
    "https://billgates.fund",
    "https://markzuckerberg.social",
    "https://larrypage.web",
    "https://sergeybrin.net",
    "https://timcook.app",
    'https://martinez-smith.org/content/articlelist.html',
    'https://www.thompson.biz/main/exploreposts.aspx',
    'https://robinson-jones.com/tags/authorview.html',
    'http://lee-wilson.com/posts/content/categorysearch.php',
    'https://anderson-davis.edu/browse/mainpage.htm',
    'https://www.linkedin.com/in/emorris',
    'https://vimeo.com/123456789',
    'http://clark-evans.net/tags/browse.html',
    'https://www.taylor.info/listing/indexcontent.html',
    'http://www.moore-hall.biz/wp-content/main/explore.php',
    'https://www.bailey.org/web/articles/showarticle.html',
    'http://mitchell-walker.net/app/browseauthor.php',
    'https://www.instagram.com/jdoe',
    'http://www.brown-king.net/tags/content/viewpost.php',
    'https://www.perez.com/app/exploresection.html',
    'https://www.flickr.com/photos/janedoe',
    'http://www.wilson-thomas.org/content/main/exploretag.html',
    'https://www.adams-lee.com/category/blog/browse.php',
    'https://www.scott-martinez.com/posts/categoryview.html',
    'https://www.twitch.tv/user1234',
    'http://www.harris-white.net/main/tag/explore.php',
    'https://johnson.com/tags/explorecategory.htm',
    'http://www.phillips-young.net/listing/contentlist.html',
    'https://www.murphy-cooper.com/main/exploreposts.aspx',
    'https://www.gonzalez.net/tags/sectionlist.html',
    'https://www.martinez-jackson.com/wp-content/main/author.php',
    'https://www.watson.com/explore/tags.html',
    'https://www.reddit.com/user/johndoe',
    'http://brooks-carter.org/browse/main.html',
    'https://www.king.edu/content/categorybrowse.html',
    'http://www.green-hill.biz/posts/content/explore.php',
    'https://www.lee.com/app/main/viewsection.php',
    'http://www.walker-young.com/tags/exploreposts.php',
    'https://www.pinterest.com/pin/123456789',
    'https://www.thomas-martinez.com/app/explorecontent.html',
    'http://www.taylor-walker.org/wp-content/tags/category.php',
    'https://www.hall.com/content/explore/tagview.html',
    'http://www.anderson-baker.com/main/taglist.php',
    'https://www.nelson.com/tags/explore.php',
    'https://www.medium.com/@janedoe',
    'http://www.carter-moore.net/content/exploresection.html',
    'https://www.reed.com/app/browseposts.html',
    'https://www.cook-morgan.org/tags/viewcategory.html',
    'http://www.bell-martinez.net/wp-content/main/exploreauthor.php',
    'https://www.russell.com/content/explore.php',
    'https://www.github.com/johndoe/repository',
    'http://www.kelly-jackson.com/main/contentlist.php',
    'https://www.griffin-johnson.com/tags/explorecontent.html',
    'https://www.wood.com/wp-content/main/tag.php',
    'https://www.linkedin.com/company/company1234',
    'http://www.turner-brown.net/app/exploremain.html',
    'https://www.ward.edu/main/exploreposts.html',
    'https://www.watson-young.com/content/category.php',
    'https://www.foster-wilson.org/tags/main/explore.php',
    'http://www.long-martin.net/app/explore.php',
    'https://www.soundcloud.com/johndoe',
    'https://www.powell.com/content/main/exploresection.html',
    'http://www.sanders-roberts.com/wp-content/tags/categoryview.php',
    'https://www.patterson.com/tags/content/browse.php',
    'https://www.stewart-baker.org/main/exploretag.php',
    'http://www.ross-parker.net/content/exploreposts.html',
    'https://www.hughes.edu/tags/explorecontent.php',
    'https://cooper-morris.gallery/portfolio/view.html',
    'http://www.jenkins-green.io/forum/thread/list.php',
    'https://www.rivera-young.tv/series/episode1.html',
    'https://www.owens.org/projects/project-a/index.html',
    'https://www.quora.com/profile/John-Doe-1',
    'https://www.palmer-barnes.academy/courses/course123.html',
    'http://www.stone-james.law/practice-areas/family-law.html',
    'https://www.bishop-ellis.fund/charities/charity123.html',
    'https://www.knight.org/events/event123/register.php',
    'https://www.gitlab.com/janedoe/project-name',
    'http://www.dunn-alexander.club/members/profile.html',
    'https://www.goodreads.com/author/show/123456.John_Doe',
    'https://www.wagner-cruz.coffee/beans/origin.html',
    'https://www.bates-lee.yoga/classes/beginner.html',
    'http://www.olson-wells.energy/solutions/solar-power.html',
    'https://www.hubbard-richardson.tech/startups/startup123.html',
    'https://www.sims-thompson.estate/properties/property123.html',
    'https://www.myers-walsh.io/dev/projects/project1.html',
    'http://www.gibson-payne.vote/campaigns/campaign123.html',
    'https://www.mccoy-jennings.space/missions/mission123.html',
    'https://www.stone-jordan.art/artists/artist123.html',
    'https://www.manning-burke.toys/products/product123.html',
    'https://www.norman-kelly.pets/dogs/breed123.html',
    'http://www.holt-warren.wedding/planning/venue123.html',
    'https://www.fleming-morrison.ink/writing/novel123.html',
    'https://www.ballard-duncan.fish/aquariums/aquarium123.html',
    'https://www.schneider-lane.bike/trails/trail123.html',
    'http://www.mcbride-floyd.fashion/shows/show123.html',
    'https://www.lambert-mccarthy.tools/power-tools/tool123.html',
    'https://www.byrd-hanson.solutions/problems/problem123.html',
    'http://www.bruce-pearson.fun/games/game123.html',
    'https://www.bowers-henderson.care/health-tips/tip123.html',
    'https://www.tanner-blake.build/constructions/project123.html',
    'https://www.finley-knight.cloud/services/service123.html',
    'http://www.gross-mcgee.wiki/topics/topic123.html',
    'https://www.dawson-lucas.chat/rooms/room123.html',
    'https://www.larson-mills.menu/recipes/recipe123.html',
    'http://www.blair-boyd.garden/plants/plant123.html',
    'https://www.savage-mccormick.vote/issues/issue123.html',
    'https://www.hardin-ferguson.repair/appliances/appliance123.html',
    'http://www.gaines-wallace.show/talkshows/show123.html',
    'https://www.blackburn-fitzgerald.city/tours/tour123.html',
    'https://www.cunningham-griffiths.band/musics/song123.html',
    'http://www.parks-meadows.life/blog/post123.html',
    'https://www.walls-stanton.game/reviews/review123.html',
    'https://www.barrett-mckinney.photo/albums/album123.html',
    'http://www.duffy-orr.club/events/event123.html',
    'https://www.stuart-casey.store/products/product123.html',
    'https://www.golden-giles.support/faq/faq123.html',
    'http://www.nash-becker.world/travel/trip123.html',
    'https://www.simon-garza.kitchen/recipes/recipe123.html',
    'https://www.gilbert-mcfarland.guide/tips/tip123.html',
    'http://www.workman-lang.agency/clients/client123.html',
    'https://www.solomon-morse.date/ideas/idea123.html',
    'https://www.conner-beard.health/conditions/condition123.html',
    'http://www.bauer-woods.film/movies/movie123.html',
    'https://www.orr-harding.dance/styles/style123.html',
    'https://www.huff-mcconnell.news/articles/article123.html',
    'https://www.velazquez-booth.fun/activities/activity123.html',
    'http://www.lawson-wade.learn/subjects/subject123.html',
    'https://www.sweet-frost.talk/discussions/discussion123.html',
    'https://www.pratt-moses.camp/camps/camp123.html',
    'https://morales-cooper.edu/listing/explore/coursesindex.html',
    'http://gutierrez-patel.net/search/category/authorhome.php',
    'https://www.nguyen.biz/sections/tags/explorecontent.jsp',
    'http://www.ramirez-johnson.com/tags/wp-content/sectionpost.asp',
    'https://www.chen.org/explore/wp-content/themes/taglist.html',
    'http://www.liu-sanchez.com/main/browse/registerpage.html',
    'https://www.twitch.tv/gamer1234',
    'https://kim-robinson.space/main/explore/postgallery.html',
    'https://soundcloud.com/user-1234567890',
    'http://www.wang-thompson.net/categories/browse/homepage.html',
    'https://www.linkedin.com/in/john-doe-123456789',
    'https://www.wilson-hughes.com/tag/explore/privacysettings.htm',
    'https://www.pinterest.com/pin/123456789012345678/',
    'http://martinez-brown.club/info/aboutus.asp',
    'https://www.instagram.com/creativeprofile/',
    'https://medium.com/@username/article-title-1234567890abcdef',
    'https://www.watson-davis.store/categories/tags/productregister.html',
    'http://www.lee-wilson.tech/search/wp-content/userguide.php',
    'https://rodriguez-martinez.health/explore/section/healthtips.jsp',
    'https://www.reddit.com/r/subredditname/comments/1234567/title_of_the_post/',
    'http://garcia-thomas.pro/list/wp-content/themes/explore.php',
    'https://www.martinez-jackson.finance/tags/browse/investments.html',
    'https://www.behance.net/gallery/123456789/Project-Title',
    'http://www.young-kim.law/main/explore/legaladvice.asp',
    'https://www.flickr.com/photos/username/12345678901/',
    'https://www.tumblr.com/blog/view/blogname/123456789012345678',
    'http://clark-edwards.digital/explore/tags/usercontent.html',
    'https://www.goodreads.com/book/show/1234567.Book_Title',
    'http://lopez-hall.games/category/browse/gamereviews.htm',
    'https://www.quora.com/What-is-an-example-question',
    'https://hall-garcia.cafe/menu/explore/specials.jsp',
    'https://www.etsy.com/listing/123456789/handmade-item-title',
    'http://www.phillips-allen.news/main/explore/breakingnews.html',
    'https://www.wright-young.shop/tags/wp-content/deals.asp',
    'https://github.com/username/repositoryname',
    'https://www.perez-martinez.wedding/gallery/browse/album123.html',
    'https://smith-jones.bio/explore/category/lifestories.jsp',
    'http://www.white-brown.fitness/programs/wp-content/workouts.php',
    'https://www.linkedin.com/company/companyname/',
    'https://www.vimeo.com/1234567890',
    'http://www.gonzalez-robinson.education/lessons/tags/courselist.html',
    'https://jackson-miller.travel/explore/tags/destinationguides.htm',
    'https://www.lee-wilson.art/portfolio/view/artwork123.jsp',
    'https://www.tripadvisor.com/UserReview-g123456-d1234567-r12345678-Hotel_Name-City_Region.html',
    'http://www.king-thomas.green/eco/wp-content/sustainability.php',
    'https://miller-davis.house/listings/wp-content/hometour.asp',
    'http://www.harris-scott.auto/explore/tags/modelreviews.html',
    'https://www.stumbleupon.com/content/1234567abc',
    'https://www.yelp.com/biz/business-name-city',
    'http://www.anderson-murphy.crafts/gallery/browse/craftideas.htm',
    'https://www.zillow.com/homedetails/1234567890_zpid/',
    'https://www.ancestry.com/family-tree/person/tree/123456789/person/12345678901/facts',
    'http://www.jones-williams.design/portfolio/wp-content/designs.php',
    'https://www.discogs.com/artist/123456-Artist-Name',
    'http://www.moore-thompson.events/main/explore/upcomingevents.asp',
    'https://www.500px.com/photo/123456789/photography-title-by-username',
    'https://www.academia.edu/12345678/Title_of_the_Paper',
    'http://www.kelly-peterson.music/explore/wp-content/albumreviews.html',
    'https://www.dribbble.com/shots/123456789/Design-Title',
    'https://www.foursquare.com/v/venue-name/1234567890',
    'https://www.mixcloud.com/username/track-title/',
    'http://www.walker-evans.photography/gallery/tags/photocollection.htm',
    'https://smith-jones.com/profiles/john-smith',
    'http://www.adams-lee.edu/alumni/1985/janedoe',
    'https://www.instagram.com/emily1990/',
    'http://www.patel-law.com/our-team/ajaypatel',
    'https://www.twitter.com/alex1984',
    'http://robertson-associates.net/about-us/meet-the-team/sarah-robertson',
    'https://www.pinterest.com/samuel_art/',
    'http://www.wilson-architects.com/portfolio/jane-wilson',
    'https://medium.com/@charlie_brown',
    'http://www.kim-chen.industries/about-us/leadership/jimmy-kim',
    'https://www.reddit.com/user/mike_hikes',
    'http://www.lopez-garcia.com/publications/lopez-research',
    'https://www.vimeo.com/channels/steve1985',
    'http://www.green-woods.com/blog-post/entryid/45/eco-friendly-designs-by-linda',
    'https://www.tumblr.com/blog/view/artbylucy89',
    'http://www.murphy-consulting.com/contact-us/murphy',
    'https://www.github.com/johndoe/projects',
    'http://www.cookingwithsandra.com/recipe/sandra-special',
    'https://www.flickr.com/photos/david_photos/',
    'http://www.brown.edu/community/jessica-b',
    'https://www.behance.net/kelly_designs',
    'http://www.morgan-photography.com/gallery/morgan-travels',
    'https://www.dribbble.com/sam_graphics',
    'http://www.ellis-law.com/our-team/ellis',
    'https://www.goodreads.com/user/show/5678910-chris-booklover',
    'http://www.fisher-woodworks.com/our-creations/john-fisher',
    'https://www.last.fm/user/emily_sings',
    'http://www.perez-arts.com/exhibitions/perez',
    'https://www.soundcloud.com/djamy',
    'http://www.thompson-travel.com/blog/travel-tips-by-karen',
    'https://www.strava.com/athletes/1234567',
    'http://www.watson-cpa.com/our-team/watson',
    'https://www.etsy.com/shop/LisasHandmadeCrafts',
    'http://www.fernandez-dentistry.com/our-staff/dr-fernandez',
    'https://www.bandcamp.com/therockband',
    'http://www.carter-designs.com/portfolio/carter',
    'https://www.deviantart.com/janeart',
    'http://www.evans-landscaping.com/our-work/evans-projects',
    'https://www.fanfiction.net/~michaelwrites',
    'http://www.gonzalez-construction.com/projects/ana-gonzalez',
    'https://www.kickstarter.com/profile/creativejames',
    'http://www.lee-photography.com/featured-shoots/lee-highlights',
    'https://www.quora.com/profile/Rachel-Advisor',
    'http://www.ramirez-solutions.com/testimonials/ramirez-feedback',
    'https://www.slideshare.net/DanielPresentations',
    'http://www.taylor-finance.com/about-us/mark-taylor',
    'https://www.ancestry.com/family-tree/person/tree/12345678/person/234567890',
    'http://www.vasquez-law.com/our-attorneys/elena-vasquez',
    'https://www.wattpad.com/user/SophieWrites',
    'http://www.young-enterprises.com/our-team/young',
    'https://www.zumba.com/en-US/member/maria-zumba',
    'http://www.baker-realty.com/listings/propertyid/1234',
    'https://www.couchsurfing.com/people/john-traveller',
    'http://www.dunn-crafts.com/about-me',
    'https://www.edx.org/bio/jane-doe',
    'http://www.fernandez-music.com/about/fernandez',
    'https://www.garcia-recipes.com/my-favorite-dish',
    'http://www.harris-consulting.com/our-clients/harris-case-studies',
    'https://www.italki.com/user/3456789',
    'http://www.johnson-lawfirm.com/our-team/lisa-johnson',
    'https://www.khanacademy.org/profile/kaid_1234567890/',
    'http://www.lopez-studio.com/our-art/lopez-gallery',
    'https://www.mooc.org/user/9876543',
    'http://www.nelson-architects.com/our-projects/nelson-designs',
    'https://www.openclassrooms.com/members/98765michelle',
    'http://www.patel-dentistry.com/meet-dr-patel',
    'https://www.quizlet.com/john_teaches',
    'http://rodriguez-publishing.com/main/contact-us.html',
    'https://www.khan-academy.org/profiles/steve_math_tutor',
    'http://martinez-designs.com/portfolio/interior-designs',
    'https://www.ebay.com/usr/linda_antiques',
    'http://www.walker-consulting.com/services/strategy-planning',
    'https://github.com/patricia-code/projects',
    'http://www.rivera-law.com/cases/case-studies',
    'https://vimeo.com/user12456/videos',
    'http://www.anderson-events.com/events/upcoming',
    'https://www.strava.com/athletes/123456789',
    'http://www.thomas-cook.com/travel-blog/tom-travels',
    'https://www.goodreads.com/author/show/123456.Lisa_Writer',
    'http://www.ward-photography.com/gallery/landscape',
    'https://dribbble.com/shots/favorite/12345678',
    'http://www.reyes-art.com/exhibits/current',
    'https://www.slideshare.net/secret/1234567890abcdef',
    'http://www.kelly-law.com/our-team/john-kelly',
    'https://etsy.me/2ABC1234',
    'http://www.cruz-construction.com/projects/commercial',
    'https://www.deviantart.com/maria-arts/gallery/',
    'http://www.barnes-legal.com/our-attorneys/sarah-barnes',
    'https://www.last.fm/user/dj_dave',
    'http://www.russell-tech.com/blog/innovation-in-tech',
    'https://www.behance.net/gallery/123456789/Creative-Designs',
    'http://www.jenkins-family.com/family-reunion-2023',
    'https://www.pinterest.com/pin/123456789012345678/',
    'http://www.alexander-research.com/publications/recent',
    'https://www.kickstarter.com/profile/creative_project123',
    'http://www.gomez-therapy.com/services/individual-counseling',
    'https://soundcloud.com/user-123456789/tracks',
    'http://www.harper-biz.com/case-studies/small-business-growth',
    'https://www.quora.com/profile/Anna-Expert',
    'http://www.ford-architecture.com/projects/residential',
    'https://www.tumblr.com/blog/view/creative-soul',
    'http://www.bailey-music.com/tour-dates',
    'https://www.reddit.com/user/tech_guru',
    'http://www.watson-cpa.com/team/jane-watson',
    'https://www.flickr.com/photos/12345678@N00/',
    'http://www.nguyen-dental.com/meet-dr-nguyen',
    'https://www.bandcamp.com/album/1234567',
    'http://www.parker-sports.com/highlights/2023-season',
    'https://medium.com/@writer_mike',
    'http://www.hughes-education.com/courses/online-learning',
    'https://www.fanfiction.net/~fantasywriter123',
    'http://www.fernandez-cuisine.com/menu/signature-dishes',
    'https://www.vimeo.com/channels/1234567',
    'http://www.jordan-consulting.com/solutions/technology-advancements',
    'https://www.ancestry.com/family-tree/person/tree/87654321/person/2345678901/facts',
    'http://www.kim-fitness.com/classes/schedule',
    'https://www.zumba.com/en-US/profile/member/123456789',
    'http://www.chen-photography.com/portfolio/events',
    'https://www.couchsurfing.com/people/laura-adventurer',
    'http://www.davis-engineering.com/projects/completed',
    'https://www.edx.org/bio/prof-johnson',
    'http://www.evans-gardening.com/blog/spring-planting-tips',
    'https://www.garcia-recipes.com/blog/recipe-of-the-month',
    'http://www.harris-lawfirm.com/about-us/attorneys/diane-harris',
    'https://www.italki.com/teacher/1234567890english',
    'http://www.johnson-photography.com/albums/weddings',
    'https://www.khanacademy.org/profile/kaid_987654321/',
    'http://www.lopez-studio.com/portfolio/fashion',
    'https://www.mooc.org/courses/advanced-python',
    'http://www.nelson-architects.com/about-us/team',
    'https://www.openclassrooms.com/members/12345caroline',
    'http://www.patel-dentistry.com/contact/location',
    'https://www.quizlet.com/class/6789012',
    'https://www.cooper-arts.com/gallery/view/paintings',
    'http://bennett-science.org/research/article/quantum-mechanics',
    'https://www.murphy-law.com/cases/civil-rights',
    'http://www.phillips-finance.com/news/update/market-trends',
    'https://www.ward-education.com/courses/advanced-algebra',
    'http://fleming-events.com/upcoming/conferences/tech-innovation',
    'https://www.grant-realty.com/listing/view/home-sales',
    'http://www.ross-dentistry.com/appointments/new-patient',
    'https://www.watson-tech.com/blogs/ai-research',
    'http://www.fernandez-foods.com/recipes/family-traditions',
    'https://www.payne-consulting.com/services/business-strategy',
    'http://www.rice-law.com/legal-blog/bankruptcy-advice',
    'https://www.sullivan-photography.com/portfolio/weddings',
    'http://www.brooks-construction.com/projects/completed',
    'https://www.hughes-education.com/courses/programming-languages',
    'http://www.gibson-music.com/tours/upcoming-shows',
    'https://www.perez-arts.com/exhibitions/current-show',
    'http://www.crawford-therapy.com/services/couples-counseling',
    'https://www.bishop-sports.com/highlights/season-recap',
    'http://www.dunn-consulting.com/expertise/innovation-management',
    'https://www.fox-news.com/category/tech/latest-in-tech',
    'http://www.george-realty.com/properties/residential',
    'https://www.hansen-architects.com/projects/urban-design',
    'http://www.owens-education.com/blog/education-trends',
    'https://www.jenkins-law.com/areas-of-practice/estate-planning',
    'http://www.knight-engineering.com/services/civil-engineering',
    'https://www.lucas-arts.com/workshops/upcoming',
    'http://www.mason-fitness.com/classes/yoga-schedule',
    'https://www.neal-tech.com/articles/future-of-robotics',
    'http://www.obrien-consulting.com/case-studies/marketing-strategies',
    'https://www.palmer-design.com/portfolio/graphic-design',
    'http://www.quinn-health.com/blog/wellness-tips',
    'https://www.reed-law.com/testimonials/client-stories',
    'http://www.shaw-photography.com/gallery/landscape',
    'https://www.tucker-legal.com/resources/legal-guides',
    'http://www.underwood-arts.com/classes/painting-techniques',
    'https://www.vargas-consulting.com/insights/industry-analysis',
    'http://www.wallace-education.com/seminars/upcoming-events',
    'https://www.xavier-research.com/publications/scientific-papers',
    'http://www.young-law.com/blog/legal-updates',
    'https://www.zimmerman-architecture.com/projects/commercial',
    'http://www.andrews-tech.com/support/faq',
    'https://www.blake-realty.com/agents/team',
    'http://www.carson-finance.com/tips/investment-strategies',
    'https://www.douglas-therapy.com/approach/therapeutic-methods',
    'http://www.elliott-consulting.com/projects/development',
    'https://www.franklin-education.com/courses/online-learning',
    'http://www.greene-construction.com/portfolio/new-construction',
    'https://www.horton-law.com/practice-areas/family-law',
    'http://www.irwin-arts.com/gallery/recent-works',
    'https://www.kelley-consulting.com/blog/strategy-insights',
    'http://www.lambert-design.com/services/interior-design',
    'https://www.mccoy-photography.com/albums/travel',
    'http://www.nolan-engineering.com/disciplines/mechanical-engineering',
    'https://www.oconnor-realty.com/properties/commercial-listings',
    'http://www.patterson-health.com/articles/mental-health',
    'https://www.ramos-law.com/news/legal-trends',
    'http://www.schwartz-consulting.com/expertise/data-analytics',
    'https://www.tate-legal.com/clients/success-stories',
    'http://www.upchurch-architecture.com/about/our-team',
    'https://www.vaughn-fitness.com/blog/healthy-living',
    'http://www.weber-education.com/certifications/it-certifications',
    'https://www.xu-research.com/findings/new-studies',
    'http://www.yates-construction.com/about/history',
    'https://www.zuniga-law.com/firm-overview',
    'http://www.fletcher-arts.com/collections/new-arrivals',
    'https://www.griffin-technology.com/blog/latest-gadgets',
    'http://www.harvey-law.com/legal-advice/family-matters',
    'https://www.ingram-publishing.com/new-releases',
    'http://www.jacobs-education.com/webinars/upcoming-sessions',
    'https://www.klein-design.com/portfolio/branding-projects',
    'http://www.lawrence-fitness.com/workout-plans/beginners',
    'https://www.maxwell-realty.com/listings/luxury-homes',
    'http://www.nichols-consulting.com/white-papers/tech-trends',
    'https://www.owen-music.com/discography/recent-albums',
    'http://www.payne-photography.com/events/recent-shoots',
    'https://www.quinn-tech.com/support/troubleshooting',
    'http://www.riley-games.com/new-releases/console-games',
    'https://www.sanders-law.com/case-studies/personal-injury',
    'http://www.thompson-travel.com/destinations/exotic-places',
    'https://www.upton-architecture.com/projects/residential-design',
    'http://www.vance-consulting.com/blog/industry-news',
    'https://www.walsh-education.com/subjects/mathematics',
    'http://www.xavier-photography.com/galleries/nature-photography',
    'https://www.york-engineering.com/services/environmental',
    'http://www.zimmerman-events.com/upcoming/music-festivals',
    'https://www.abbott-law.com/areas-of-practice/criminal-defense',
    'http://www.baxter-sports.com/teams/varsity-soccer',
    'https://www.clarke-arts.com/classes/adult-painting',
    'http://www.douglas-consulting.com/research/market-analysis',
    'https://www.elliott-realty.com/properties/beachfront',
    'http://www.flynn-therapy.com/approach/cognitive-behavioral',
    'https://www.garrett-design.com/case-studies/website-redesign',
    'http://www.holmes-photography.com/portfolio/portraits',
    'https://www.ivey-construction.com/projects/commercial-buildings',
    'http://www.joyce-law.com/publications/legal-articles',
    'https://www.kramer-education.com/courses/data-science',
    'http://www.lloyd-finance.com/advice/investment-tips',
    'https://www.manning-music.com/tours/european-tour',
    'http://www.norton-architecture.com/blog/sustainable-design',
    'https://www.oakley-consulting.com/testimonials/client-success',
    'http://www.palmer-photography.com/collections/urban-landscapes',
    'https://www.quincy-law.com/resources/legal-guides',
    'http://www.ramirez-foods.com/blog/healthy-eating',
    'https://www.shepard-design.com/projects/commercial-portfolio',
    'http://www.todd-law.com/faq/personal-injury-questions',
    'https://www.vaughan-education.com/programs/online-courses',
    'http://www.wallace-tech.com/products/new-releases',
    'https://www.winters-photography.com/albums/wedding-collection',
    'http://www.yates-construction.com/news/construction-updates',
    'https://www.zachary-realty.com/featured/properties',
    'http://www.adler-arts.com/workshops/creative-writing',
    'https://www.briggs-consulting.com/solutions/business-optimization',
    'http://www.caldwell-engineering.com/disciplines/structural',
    'https://www.dunn-research.com/projects/innovative-solutions',
    'http://www.estes-education.com/learning/online-learning',
    'https://www.frank-realty.com/neighborhoods/up-and-coming',
    'http://www.gill-law.com/practice-areas/estate-planning',
    'https://www.hammond-photography.com/gallery/landscape',
    'http://www.irwin-sports.com/highlights/2023-season',
    'https://www.kennedy-design.com/portfolio/residential-projects',
    'http://www.larson-health.com/blog/fitness-trends',
    'https://www.mccarthy-consulting.com/case-study/brand-strategy',
    'http://www.newman-law.com/legal-tips/consumer-rights',
    'https://www.osborne-arts.com/exhibits/upcoming',
    'http://www.pierce-architecture.com/works/commercial-design',
    'https://www.raymond-education.com/seminars/leadership-skills',
    'http://www.stuart-photography.com/sessions/newborn',
    'https://www.tanner-consulting.com/insights/market-research'
]


STREET_ADDRESS_LIST = [
    '591 Smith Centers Apt. 656\nJoshuamouth, RI 95963',
    '743 Erika Bypass Apt. 419\nAndreahaven, IL 54207',
    '1028 Johnson Isle Suite 210\nNew Michael, TX 75001',
    '3887 Jessica Turnpike\nLake Jennifer, CA 94043',
    '450 Adams Estate\nEast Christopher, FL 32104',
    '67 Brown Road\nSouth Rebecca, NY 10001',
    '9846 Miller Junctions\nPort Davidtown, CO 80202',
    '4319 Emily Brooks\nNorth Jason, MI 48127',
    '227 Laura Inlet\nWest Rachelburgh, VA 24502',
    '7138 Sarah Grove Apt. 303\nEast Daniel, GA 30301',
    '6584 Thomas Loaf\nKevinshire, WA 98101',
    '8927 Alexander Path Suite 120\nLake Matthew, AZ 85001',
    '1768 Nicole Cliff\nDavishaven, NJ 07001',
    '5467 White Mission\nNew Jonathanville, NV 89501',
    '3659 Brittany Stream\nPort Angela, PA 19019',
    '591 Smith Centers Apt. 656\nJoshuamouth, RI 95963, USA',
    '743 Erika Bypass Apt. 419\nAndreahaven, IL 54207, USA',
    '88 Kingsway\nLondon WC2B 6AA, UK',
    '12 Rue de l\'École\n75005 Paris, France',
    'Block 5, Unit 3, Garden Estate\nNairobi, Kenya',
    '5/7 Yaroslaviv Val Street\nKyiv, 01901, Ukraine',
    'Unit 10, 25 Smith St\nFitzroy, VIC 3065, Australia',
    '5003 Maçka Cd.\nŞişli, Istanbul 34367, Turkey',
    'Calle Ocho 45\nHavana, Cuba',
    '98 Rua de São Bento\n1200-821 Lisboa, Portugal',
    'Apt. 202, Higashi 4-chome\nSapporo, Hokkaido 060-0041, Japan',
    '4500 Paseo de la Reforma\nCiudad de México, CDMX 06500, Mexico',
    'Viale Regina Margherita, 6\n00198 Roma RM, Italy',
    'B-14, Second Floor\nChandni Chowk, New Delhi, 110006, India',
    '89 Jalan Hang Jebat\n75200 Melaka, Malaysia',
    'Lote 4, Av. dos Pescadores\nLuanda, Angola',
    '591 Smith Centers Apt. 656\nJoshuamouth, RI 95963, USA',
    '743 Erika Bypass Apt. 419\nAndreahaven, IL 54207, USA',
    '22 Windsor Road\nBelfast BT9 7FB, Northern Ireland',
    '45 The Esplanade\nPerth WA 6000, Australia',
    '108 St. George Street\nToronto, ON M5S 1A6, Canada',
    '3 Chancery Lane\nHamilton HM 12, Bermuda',
    '88 High Street\nAuckland 1010, New Zealand',
    '5 Tafawa Balewa Road\nLagos, Nigeria',
    '17 Queen Elizabeth Drive\nSuva, Fiji',
    'Unit 5, 67 Spring Street\nHobart TAS 7000, Australia',
    'Block 3B, Flat 7\nGreenwich Estate, Nairobi, Kenya',
    '102 Long Lane\nLondon EC1A 9ET, UK',
    '27 Ocean View Drive\nCape Town 8005, South Africa',
    '1234 Maple Avenue\nKingston, Jamaica',
    '67 Upper Cross Street\nSingapore 058327',
    '4 Merbau Road\nPort Moresby, Papua New Guinea',
    '19 Independence Avenue\nAccra, Ghana',
    '8 Cathedral Square\nChristchurch 8011, New Zealand',
    '56 St. John\'s Wood Road\nBridgetown, Barbados',
    '3 Harbour Road\nVictoria, Mahe, Seychelles',
    '45 O\'Connell Street\nDublin 1, Ireland',
    '100 King Street West\nToronto, ON M5X 1K7, Canada',
    '12 Ocean Pathway\nGeorgetown, Guyana',
    '67 Church Street\nHamilton, Bermuda',
    '22 Garden Avenue\nKingston 6, Jamaica',
    "Cherry Orchard Estate, Flat 7B\nBridgetown, Barbados",
    "Maplewood Drive, Unit 12\nChristchurch, New Zealand",
    "Rosewood Terrace, House 8\nDublin, Ireland",
    "Lavender Lane, Suite 200\nToronto, Ontario, Canada",
    "Eucalyptus Grove, Villa 5\nSydney, New South Wales, Australia",
    "Sycamore Heights, Bungalow 16\nLondon, United Kingdom",
    "Palm Court, Apartment 3C\nNassau, Bahamas",
    "Willow Way, Duplex 4\nAuckland, New Zealand",
    "Birchwood Close, Townhouse 10\nEdinburgh, Scotland",
    "Cedar Vale, Maisonette 6\nKingston, Jamaica",
    "Hawthorn Crescent, Flat 21\nBelfast, Northern Ireland",
    "Magnolia Mews, Studio 30\nVancouver, British Columbia, Canada",
    "Olive Branch Lane, Unit 2A\nBrisbane, Queensland, Australia",
    "Pine Knoll, Cottage 7\nCape Town, South Africa",
    "Redwood Rise, Condo 19\nHamilton, Bermuda",
    "Silver Birch Square, Loft 9\nWellington, New Zealand",
    "Aspen Alley, Penthouse 5\nCork, Ireland",
    "Juniper Junction, Bungalow 11\nManchester, United Kingdom",
    "Spruce Street, Suite 14\nNairobi, Kenya",
    "Teakwood Trail, Villa 3\nFreeport, Bahamas",
    "Walnut Walk, Townhouse 22\nOttawa, Ontario, Canada",
    "Acacia Avenue, Apartment 8D\nMelbourne, Victoria, Australia",
    "Banyan Boulevard, House 27\nBridgetown, Barbados",
    "Cypress Circle, Duplex 6\nAberdeen, Scotland",
    "Dogwood Drive, Condo 31\nKingston, Jamaica",
    "Elm Estates, Flat 12\nGalway, Ireland",
    "Fir Field, Cottage 9\nChristchurch, New Zealand",
    "Gum Grove, Maisonette 2B\nNassau, Bahamas",
    "Holly Harbour, Loft 18\nToronto, Ontario, Canada",
    "Ivy Island, Studio 23\nSydney, New South Wales, Australia",
    "Jasmine Junction, Penthouse 10\nDublin, Ireland",
    "Kauri Cliffs, Villa 14\nAuckland, New Zealand",
    "Lilac Lane, Townhouse 5\nLondon, United Kingdom",
    "Myrtle Meadows, Apartment 20\nVancouver, British Columbia, Canada",
    "Nectarine Nook, Bungalow 4\nBrisbane, Queensland, Australia",
    "Oak Overlook, Suite 17\nCape Town, South Africa",
    "Peach Plaza, Condo 28\nHamilton, Bermuda",
    "Quince Quarter, Loft 6\nWellington, New Zealand",
    "Raspberry Row, Flat 13\nCork, Ireland",
    "Strawberry Street, Duplex 21\nManchester, United Kingdom",
    "Tangerine Terrace, House 8\nNairobi, Kenya",
    "Umbrella Upland, Villa 15\nFreeport, Bahamas",
    "Vanilla Vale, Townhouse 32\nOttawa, Ontario, Canada",
    "Watermelon Way, Apartment 1A\nMelbourne, Victoria, Australia",
    "Xylophone Xing, Cottage 7\nBridgetown, Barbados",
    "Yucca Yard, Maisonette 24\nAberdeen, Scotland",
    "Zinnia Zone, Studio 11\nGalway, Ireland"
]

ID_NUM_LIST = [
    '947563821045',
    '324786213908',
    '981236547025',
    '274819536485',
    'Xz:482930571829',
    '621384975120',
    'Jk:739182543610',
    '827364192083',
    'Fg:916273845701',
    '482736495017',
    'Yt:312987546802',
    '729183645291',
    'Bv:618273940572',
    '193847562810',
    'Lp:482736495176',
    '638291745028',
    'Rt:528374916283',
    '847362519403',
    'Mn:293847561729',
    '192837465028',
    'Zx:374829163547',
    '648291735092',
    'Cv:182736495807',
    '739182546201',
    'Xr82-394857-AB',
    'Ym76:218749-DZ',
    'Zx54_937615-EF',
    'Wv32.846193-GH',
    'Uj21+729384-IJ',
    'Tk09-518472-KL',
    'Si98:647291-MN',
    'Rq76_825634-OP',
    'Pf54.394817-QR',
    'Od32+218749-ST',
    'Nc09-937615-UV',
    'Mb98:846193-WX',
    'La76_729384-YZ',
    'Kz54.518472-AB1',
    'Jy32+647291-CD2',
    'gT3+Rq0:835^MN',
    'hS2_Pf9.947&OP',
    'iR1|Od8+059*QR',
    'jQ0:Zo7.163^ST',
    'kP9+Yn6|271&UV',
    'lO8:Io5.385^WX',
    'mN7+Hw4|493*YZ',
    'nM6_Gv3:507^AB1',
    'oL5|Fu2.621&CD2',
    'pK4+Et1:739^EF3',
    'qJ3|Ds0.853&GH4',
    'rI2:Cr9+967^IJ5',
    '726491837',
    '382719654',
    '593817264',
    '471283956',
    '827364195',
    '918273645',
    '364819275',
    '582736491',
    '193827546',
    '621385094233',
    'XF-2948',
    'Pl:392840582901',
    '847392053982',
    '76,54,32,1',
    '003928475612',
    'LV-9301',
    'Un:482039582019',
    '482930583210',
    '29,48,76,5',
    'AC-1928',
    '943857192837',
    'Ti:294857193847',
    '192837465920',
    '07,62,85,3',
    'ZP-4839',
    '483920102938',
    'Mn:495820394857',
    '850294857123',
    '365120938475', 'BV-4873', 'Op:294857204857', '193847562930',
    '21,63,84,7', '482930580102', 'JK-2048', 'Gt:748392057483',
    '574839201938', '38,47,29,1', '927483920475', 'LM-5930',
    'Fr:203948576382', '948572039485', '49,58,73,2', '029384750293',
    'QR-8302', 'Hy:930285748392', '384750293847', '56,73,91,4',
    '758392048573', 'NS-1948', 'Jv:485720394857', '203948572048',
    '64,82,95,3', '847593020394', 'TW-4891', 'Kc:394857293847',
    '948573920102', '73,85,92,6', '293847593020', 'UX-2937',
    'Ld:102938475839', '384750293018', '82,94,07,5', '758392019283',
    'VY-7483', 'Me:948572039485', '102938475839', '91,03,14,7',
    '293847582039', 'WZ-3928', 'Nf:384750293847', '849572039485',
    '05,16,27,8', '938475820394', 'XA-4839', 'Og:758392048573',
    '294857203948', '19,20,31,9', '475839201938', 'YB-5748',
    'Ph:293847593020', '384750293847', '23,34,45,0', '758392019384',
    'ZC-6657', 'Qi:102938475839', '948572039485', '37,48,59,1',
    '293847582039', 'AD-7768', 'Rj:384750293847', '758392048573',
    '41,52,63,2', '839201938475', 'BE-8879', 'Sk:294857203948',
    '102938475839', '55,66,77,3', '847593020394', 'CF-9980',
    'Tl:475839201938', '294857203948', '69,70,81,4', '938475820394',
    'DG-1029', 'Um:758392048573', '384750293847', '83,94,05,5',
    '839201938475', 'EH-2130', 'Vn:294857203948', '475839201938',
    '07,18,29,6', '847593020394', 'FI-3241', 'Wo:102938475839',
    '758392048573', '21,32,43,7', '293847582039', 'GJ-4352',
    'Xp:384750293847', '294857203948', '35,46,57,8', '839201938475',
    'HK-5463', 'Yq:475839201938', '102938475839', '49,50,61,9',
    '847593020394', 'IL-6574', 'Zr:758392048573', '384750293847',
    '63,74,85,0', '938475820394', 'JM-7685', 'As:294857203948',
    '472930183746', 'XC-2910', 'Dv:827364591028', '629381047563',
    '84,29,13,7', '183746293810', 'YD-3821', 'Ew:746283910472',
    '738291056482', '95,10,24,8', '294817365920', 'ZE-4732',
    'Fx:918273645829', '847362918405', '06,11,35,9', '365928174638',
    'AF-5643', 'Gy:382917465920', '918274638291', '17,22,46,0',
    '473829105684', 'BG-6554', 'Hz:294810576382', '829146382917',
    '28,33,47,1', '576382914063', 'CH-7465', 'Ia:473829105684',
    '638291047382', '39,44,58,2', '105684729318', 'DI-8376',
    'Jb:576382914063', '291847362918', '50,55,69,3', '729318476293',
    'EJ-9287', 'Kc:638291047382', '382914063829', '61,66,70,4',
    '184763829105', 'FK-0198', 'Ld:291847362918', '914063829146',
    '72,77,81,5', '836291847362', 'GL-1209', 'Me:184763829105',
    '063829146382', '83,88,92,6', '472918365829', 'HM-2310',
    'Nf:836291847362', '291047382914', '94,99,03,7', '918365829174',
    'IN-3421', 'Og:472918365829', '847362918473', '05,10,14,8',
    '365829174638', 'JO-4532', 'Ph:918365829174', '382914063829',
    '16,21,25,9', '829174638291', 'KP-5643', 'Qi:365829174638',
    '914063829176', '27,32,36,0', '174638291847', 'LQ-6754',
    'Rj:829174638291', '063829176914', '38,43,47,1', '638291847362',
    'MR-7865', 'Sk:174638291847', '176914063829', '49,54,58,2',
    '291847362918', 'NS-8976', 'Tl:638291847362', '829176914063',
    '60,65,69,3', '847362918473', 'OT-9087', 'Um:291847362918',
    '914063829176', '71,76,80,4', '362918473829', 'PU-0198',
    'Vn:847362918473', '176914063829', '82,87,91,5', '918473829176',
    'QV-1209', 'Wo:362918473829', '063829176914', '93,98,02,6'
]
